### ISSUE TITLE
Finalizing es6 modules migration

### ISSUE THREAD

**Issue by gabesmed** [gabesmed/ember-leaflet#101]

**Comment by gabesmed** [comment]
Hey @miguelcobain just wanted to check in with you finishing the migration! Excited that seems like we're almost there. todo: updating docs/examples/class reference, testing in a production system. i'll take a look at the examples branch

**Comment by gabesmed** [comment]
@twokul do you know how we could use Ember CLI to generate a standalone (legacy) version of EmberLeaflet, where things are still accessible via a browser global?

**Comment by gabesmed** [comment]
@twokul also any thoughts in general about how we stand for the migration? anything left to do?

**Comment by twokul** [comment]
now that I think about it, maybe we should create an `ember-cli-leaflet` addon and call existing repo obsolete and not maintain it anymore saying that `ember-cli-leaflet` is a way to go and people should be upgrading their apps to Ember CLI apps.

**Comment by twokul** [comment]
we can also create `gh-pages` branch their and deploy documentation through github.

**Comment by twokul** [comment]
@gabesmed @miguelcobain ^^

**Comment by miguelcobain** [comment]
ember-cli-leaflet name taken: https://www.npmjs.com/package/ember-cli-leaflet

**Comment by twokul** [comment]
@miguelcobain even better, we can keep the name the same for both projects

**Comment by csantero** [comment]
If you guys want to use `ember-cli-leaflet` as the npm package  for the ES6 module port I'm happy to transfer ownership.

**Comment by miguelcobain** [comment]
@twokul, why not keep the current globals version in a `globals` branch?

Then we add a readme notice on how to get it.

**Comment by twokul** [comment]
@miguelcobain having two branches with two completely different structures and dependencies is a bit of a hassle. having two repos seems like a better approach IMO. @gabesmed thoughts?

**Comment by twokul** [comment]
@csantero that would be lovely, Sir.

**Comment by miguelcobain** [comment]
@twokul Right. So what about we have a new `ember-leaflet-globals` instead, and have the `ember-leaflet` repo with the es6 port?
I guess this doesn't really matter as long as we have `ember-leaflet` on npm.

**Comment by csantero** [comment]
@twokul @miguelcobain I made you owners on npm for ember-cli-leaflet. @gabesmed  I didn't see an npm user named gabesmed, so if you have a different username let me know and I'll add you.

Of course if you go with a different package name, that's cool too. =)

**Comment by twokul** [comment]
@miguelcobain that's what I'm proposing. Let's use `ember-cli-leaflet` provided by @csantero (thanks!)

**Comment by gabesmed** [comment]
whoa this went far fast....i'm not sure how i feel about having two repos with one getting swiftly out of date. happy to move repos if it helps anything but don't really see the need or improvement it brings? Couldn't we just add a build instruction to the ember cli build kit to generate a version of the EmberLeaflet  js that uses a browser global?

**Comment by gabesmed** [comment]
(sorry out of the country so a bit slow on responses)

**Comment by twokul** [comment]
@gabesmed Ember.js ecosystem is going away from globals and it makes sense for us to follow IMO

**Comment by gabesmed** [comment]
@twokul totally understood...huh so you recommend going cold turkey off it? if that's the case, we can maybe just keep this repo and have a legacy link for an old build of the globals version. don't see any need to keep it around. but *would* be useful to have something for JSfiddle

**Comment by miguelcobain** [comment]
My opinion is that the current master should live somewhere, either as a another branch or as another repo.

**Comment by gabesmed** [comment]
i don't have a strong opinion here though; whatever's best for the library in the new world of ember-cli is gonna be the best choice. @miguelcobain if you agree with @twokul then that is most likely the way to go. the only reason i see for switching repos to ember-cli-leaflet tho is if the naming convention of starting with ember-cli is important? otherwise i'd see just keeping current repo, and moving old version to an archive branch if not removing -- nobody will really need it anymore correct?

anyway don't mean to hold things up. lets just get this done in whatever way seems best.

**Comment by gabesmed** [comment]
ping! @twokul @miguelcobain any thoughts?

**Comment by miguelcobain** [comment]
Like I said before, I think `ember-leaflet` is a good and clean name.
My opinion is to have an ember-cli addon in the master branch an the current globals version in an archive branch.
We could also come up with a way to package the es6 version as globals too, separately. But in my opinion, that is not a priority.

**Comment by gabesmed** [comment]
ok...then i'm ready to switch and we can handle the documentation switch later. has anyone confirmed that the es6 version *works* in an actual app?

**Comment by miguelcobain** [comment]
Will do that ASAP.

**Comment by AW-UC** [comment]
Some quick feedback with Ember-CLI 0.2.3:
After installing the addon the component gets registered. However, calling `{{ember-leaflet}}` in a template does not properly render the map, because it has no height If I e.g. add the style `height: 1000px` to the `leaflet-container` it is rendered, but only the first row of map tiles get loaded.

**Comment by miguelcobain** [comment]
@AW-UC That `height: 1000px` on the container is expected. Leaflet behaves that way as well.

**Comment by AW-UC** [comment]
@OK. Maybe include the advise in the README to add corresponding styles for `leaflet-container`?

**Comment by miguelcobain** [comment]
I think we should include any styles for leaflet-container. People should style it according to their needs. There's nothing sensible we could include upfront, I think.

An entry in the README seems fine.

**Comment by miguelcobain** [comment]
@gabesmed I think now we're done with the migration.

Proposed plan:
- migrate globals version to a globals branch
- move ember-cli-es6 branch to master
- move new class reference to `/docs` on gh-pages branch
- publish on npm
  - current version is `0.6.1`. Following semver, we should increment major and publish version `1.0.0`.

I can get this done. :)

**Comment by gabesmed** [comment]
\o/

**Comment by gabesmed** [comment]
:ship: !!

**Comment by gabesmed** [comment]
please do the honors @miguelcobain. I'm also very much in favor of doing the global version using Ember Giftwrap -- that should help us with the example page and JSfiddle examples with the new version.

**Comment by gabesmed** [comment]
but we can do that after

**Comment by kunerd** [comment]
:+1:

**Comment by miguelcobain** [comment]
Recruiting people for input on #111.

**Comment by gabesmed** [comment]
hey peoples! i'm back! i'm using this for a project again (now on ember-cli :) so i might be more active over the next few months. merged this to master as a start!
