### ISSUE TITLE
MultiPolyline derived plugin

### ISSUE THREAD

**Issue by odix67** [gabesmed/ember-leaflet#104]
Hi,

is there a possibility to use a MultiPolyLine derived plugin, like Leaflet.Geodesic with EmberLeaflet ?

BR odi

**Comment by miguelcobain** [comment]
Currently not easy.
If we had a MultiPolyline implementation, you would only need to extend it and override `newLayer` to create `L.geodesic` layer.
You best bet currently is to subclass `EmberLeaflet.Layer`, implement `newLayer` and create it yourself.

**Comment by odix67** [comment]
ok, thanks for the tip
