### ISSUE TITLE
jsfiddle exemple broken

### ISSUE THREAD

**Issue by mylen** [gabesmed/ember-leaflet#105]
http://jsfiddle.net/3bUv8/

can't get a jsfiddle to display a map, am doing something wrong?

**Comment by srt32** [comment]
Seems like `Ember` is not getting loaded as a dependency. When I opened the console I saw, `Uncaught ReferenceError: Ember is not defined` and then when I followed the link (http://builds.emberjs.com/ember-latest.js) for the `ember-latest` dependency you had, the link was a 404. Could you try updating your Ember dependency?

**Comment by gabesmed** [comment]
Thanks for the note @mylen! Updated the JSfiddle, it should work now: http://jsfiddle.net/y524t8f8/
