### ISSUE TITLE
DEPRECATION: Action handlers contained in an `events` object are deprecated in favor of putting them in an `actions` object

### ISSUE THREAD

**Issue by Narsul** [gabesmed/ember-leaflet#115]
I'm using your `ember-cli-es6` branch and this's what I receive when I create `leaflet-map` component:
```
DEPRECATION: Action handlers contained in an `events` object are deprecated in favor of putting them in an `actions` object
```
it happens because of using field name `events` as a list of supported events, I can renamed it and it usages to `events_` and this problem disappeared and `leaflet-component` started to work fine.

I can make pull request if you'll tell me how you want to name this field

**Comment by miguelcobain** [comment]
I think that `leafletEvents` makes sense.
A PR would be great!

**Comment by Narsul** [comment]
Here it is: #116
