### ISSUE TITLE
Ember 1.13 compatibility

### ISSUE THREAD

**Issue by pedrokost** [gabesmed/ember-leaflet#118]
Upon upgrading to Ember 1.13, the leaflet code is breaking with the following message:

```
Uncaught TypeError: Cannot read property 'forEach' of undefined
```
which seems to originate from `LayerMixing` ([line 121](https://github.com/gabesmed/ember-leaflet/blob/master/packages/ember-leaflet/lib/layer.js#L121)). `get(this, 'events')` returns `undefined`.

I am using the master branch of ember-leaflet.

**Comment by miguelcobain** [comment]
Probably related with #116?

The master branch of ember-leaflet isn't maintained in favor of the existing ember-cli version.
Are you looking for a globals version of ember-leaflet?
If so, solving #108 would be the right way to go.

**Comment by pedrokost** [comment]
I am rewriting the map to the es6 branch. Closing issue.
