### ISSUE TITLE
Struggling to install ember-cli version of ember-leaflet

### ISSUE THREAD

**Issue by ianpetzer** [gabesmed/ember-leaflet#119]
Hi,

When I run 'ember install ember-leaflet' I get the following error:

    404 Not Found: ember-leaflet
    Error: 404 Not Found: ember-leaflet

Is there anything that I can do to fix this?

**Comment by miguelcobain** [comment]
To install the ember-cli-es6 branch of this project, please use the following:

```bash
$ ember install gabesmed/ember-leaflet#ember-cli-es6
```

**Comment by ianpetzer** [comment]
Great.. That worked prefectly.

Thanks so much
