### ISSUE TITLE
Ember.beforeObserver is deprecated

### ISSUE THREAD

**Issue by miguelcobain** [gabesmed/ember-leaflet#123]
> DEPRECATION: Ember.beforeObserver is deprecated and will be removed in the near future. See http://emberjs.com/deprecations/v1.x/#toc_beforeobserver for more details.

**Comment by AW-UC** [comment]
I don't receive these deprecation warnings (#122 neither). When do they occur?

**Comment by miguelcobain** [comment]
@AW-UC Both deprecations show up in my Ember 1.13.5.

Which version are you running?

**Comment by AW-UC** [comment]
Ok, then you are apparently using Ember CLI master. I am using the latest release (1.13.1) which is still on Ember 1.13.3. No deprecations there, yet.

**Comment by miguelcobain** [comment]
You don't need to use ember-cli master to use other versions of ember.

Just change ember version on bower.json.

**Comment by bobbysciacchitano** [comment]
I get the deprecation warning running Ember 1.13.8 with the same version of Ember-Cli. 

The message is: ```DEPRECATION: Ember.beforeObserver is deprecated and will be removed in the near future. See http://emberjs.com/deprecations/v1.x/#toc_beforeobserver for more details.```

Specifically affects layers/collection.js _contentWillChange.

**Comment by tostercx** [comment]
Removed in ember 2.

**Comment by floqqi** [comment]
@gabesmed: Any plans for Ember 2.0? Meanwhile it would be nice if there would be a message that 2.0 is currently not supported.

**Comment by pedrokost** [comment]
+1

**Comment by gabesmed** [comment]
taking a first pass at fixing this in https://github.com/gabesmed/ember-leaflet/pull/134 -- could use some help testing in practice as i'm worried about breaking peoples' implementations

**Comment by gabesmed** [comment]
please test me!!

**Comment by ianpetzer** [comment]
@gabesmed Awesome work! Thanks.

I can confirm that this is working for me on Ember 1.13.9 ... Ie: All of my ember-leaflet maps are working as expected and the .beforeObserver deprecation warnings are gone.

**Comment by pedrokost** [comment]
@gabesmed It is working fine for me as well on Ember 1.13.10. Thank you!

**Comment by floqqi** [comment]
@gabesmed Works for me using Ember 2.1. Thanks!
