### ISSUE TITLE
Ember-leaflet 2.0

### ISSUE THREAD

**Issue by miguelcobain** [gabesmed/ember-leaflet#141]
Ember-leaflet 2.0 was released.
- http://www.ember-leaflet.com
- https://github.com/miguelcobain/ember-leaflet

Will update npm soon.

Should this repo's README point there somehow?

**Comment by gabesmed** [comment]
HOTTTT

**Comment by jamesdixon** [comment]
Damn, well done gents!

**Comment by gabesmed** [comment]
updated
