### ISSUE TITLE
Popup width is not updated automatically when content changes

### ISSUE THREAD

**Issue by plcarmel** [gabesmed/ember-leaflet#142]
In my app, when the user clicks on a marker, a promise needs to be resolved before the popup content is rendered by Ember.

The problem is that the width seems to be computed only once (at the time the popup opens) and the popup ends-up being not wide enough for the content.

Any idea how to fix this ?

**Comment by miguelcobain** [comment]
@plcarmel are you using ember-leaflet 2.0 - www.ember-leaflet.com ?

**Comment by plcarmel** [comment]
Version 2.1.1

**Comment by miguelcobain** [comment]
@plcarmel Then this is the wrong repo. The repo is pre 2.0.

Could you open an issue there, please?

**Comment by plcarmel** [comment]
Ok, sorry about that.
