### ISSUE TITLE
ImageOverlay with dynamic bounds throws error

### ISSUE THREAD

**Issue by allthesignals** [gabesmed/ember-leaflet#144]
Hi folks,
Wondering if I could get some guesses about how to troubleshoot this:
For various reasons, I’m using `{{image-layer}}` with dynamic `bounds` property:

```
{{#leaflet-map bounds=bounds}}
  {{image-layer imageUrl="2016-07-27 Worcester Buildings 3D.png" bounds=bounds}}
  {{marker-layer lat=minLat lng=minLng draggable=true onDragend=(action "updateMin" r)}}
  {{marker-layer lat=maxLat lng=maxLng draggable=true onDragend=(action "updateMax" r)}}
{{/leaflet-map}}
```

My `bounds` is a computed property on the controller:

```
  bounds: function() {
    let minLat = parseFloat(this.get('minLat’));
    let minLng = parseFloat(this.get('minLng'));
    let maxLat = parseFloat(this.get('maxLat'));
    let maxLng = parseFloat(this.get('maxLng'));

    return L.latLngBounds([[minLat, minLng],
      [maxLat, maxLng]]);

  }.property('minLat,minLng,maxLat,maxLng’),

  actions: {
    updateMax(r,e) {
      let location = e.target.getLatLng();
      this.set('maxLat', location.lat);
      this.set('maxLng', location.lng);
    },
    updateMin(r,e) {
      let location = e.target.getLatLng();
      this.set('minLat', location.lat);
      this.set('minLng', location.lng);
    } 
  }
```

This throws: `ember.debug.js:10873 Uncaught TypeError: Cannot read property 'meta' of null`

Full stack trace:
ember.debug.js:10873 Uncaught TypeError: Cannot read property 'meta' of nullcomponentHook @ ember.debug.js:10873handleRedirect @ ember.debug.js:46519inline @ ember.debug.js:46673inline @ ember.debug.js:47200(anonymous function) @ ember.debug.js:47282dirtyCheck @ ember.debug.js:47325inline @ ember.debug.js:47281RenderResult.populateNodes @ ember.debug.js:47621RenderResult.revalidateWith @ ember.debug.js:47593validateChildMorphs @ ember.debug.js:47953dirtyCheck @ ember.debug.js:47330inline @ ember.debug.js:47281RenderResult.populateNodes @ ember.debug.js:47621RenderResult.revalidateWith @ ember.debug.js:47593validateChildMorphs @ ember.debug.js:47953dirtyCheck @ ember.debug.js:47330content @ ember.debug.js:47287RenderResult.populateNodes @ ember.debug.js:47623RenderResult.revalidateWith @ ember.debug.js:47593Block.invoke @ ember.debug.js:48160ComponentNodeManager_rerender_instrument @ ember.debug.js:14668instrument @ ember.debug.js:17047ComponentNodeManager_rerender @ ember.debug.js:14647componentHook @ ember.debug.js:10877handleRedirect @ ember.debug.js:46519block @ ember.debug.js:46491block @ ember.debug.js:47189(anonymous function) @ ember.debug.js:47276dirtyCheck @ ember.debug.js:47325block @ ember.debug.js:47275RenderResult.populateNodes @ ember.debug.js:47619RenderResult.revalidateWith @ ember.debug.js:47593validateChildMorphs @ ember.debug.js:47953dirtyCheck @ ember.debug.js:47330content @ ember.debug.js:47287RenderResult.populateNodes @ ember.debug.js:47623RenderResult.revalidateWith @ ember.debug.js:47593validateChildMorphs @ ember.debug.js:47953dirtyCheck @ ember.debug.js:47330content @ ember.debug.js:47287RenderResult.populateNodes @ ember.debug.js:47623RenderResult.revalidateWith @ ember.debug.js:47593RenderResult.revalidate @ ember.debug.js:47570Renderer_revalidateTopLevelView @ ember.debug.js:15087exports.default._emberMetalMixin.Mixin.create._Mixin$create.revalidate @ ember.debug.js:43989invoke @ ember.debug.js:990flush @ ember.debug.js:1054flush @ ember.debug.js:862end @ ember.debug.js:176(anonymous function) @ ember.debug.js:742

**Comment by allthesignals** [comment]
Related: https://github.com/Leaflet/Leaflet/pull/2436.

It may not be really part of Leaflet's API design, although I do see a setBounds() function here: https://github.com/Leaflet/Leaflet/blob/master/src/layer/ImageOverlay.js.

**Comment by miguelcobain** [comment]
@allthesignals this is a repo for leaflet 1. You probably meant to open this at https://github.com/miguelcobain/ember-leaflet

**Comment by allthesignals** [comment]
@miguelcobain

Whoops!
