### ISSUE TITLE
Ember leaflet is not displaying anything, on changing css property it shows but does not work well

### ISSUE THREAD

**Issue by jiteshgupta1995** [gabesmed/ember-leaflet#146]
I am using Ember-leaflet for my ember application. I followed every step from installation to usage but somehow it is not showing anything. I inspected the elements and found property overflow:hidden. I changed to overflow:visible then map was showing but on zooming in and out, image expands awkwardly.

I am using in my template.hbs

```
{{#leaflet-map lat=lat lng=lng zoom=zoom}}
  {{tile-layer url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}
{{/leaflet-map}}
```

and in my template.js

```
export default Ember.Controller.extend({
  lat: 45.519743,
  lng: -122.680522,
  zoom: 10
});
```
reference used from http://www.ember-leaflet.com . Do I required to import or include any CSS or JS file. Any help?

**Comment by miguelcobain** [comment]
@jiteshgupta1995 you're using the wrong repository. ember-leaflet project has moved to https://github.com/miguelcobain/ember-leaflet

**Comment by miguelcobain** [comment]
Also, feel free to join us at #e-leaflet channel on ember's slack.

**Comment by jiteshgupta1995** [comment]
@miguelcobain thanks for the reply. Will raise this issue on that repository
