### ISSUE TITLE
Layers control and CollectionLayer

### ISSUE THREAD

**Issue by miguelcobain** [gabesmed/ember-leaflet#47]
Leaflet has an unexpected (maybe not) way of hiding and showing layers on a map: it _removes_ them to hide and _adds_ them to show.
This is exactly what a [Control.Layers](http://leafletjs.com/reference.html#control-layers) does. When you activate a layer in the control, you add it to the map. When you deactivate a layer, you remove it from the map. If you want to show it again, you need to keep the reference to the layer and add it back again.

The thing is that the layers control must have _all_ layers (so that I can choose among all of them), but the map may not contain all the layers (because some of them may not be visible by default).
I need to have a layers control on my project, but I can't get my head around this issue. What's missing in Ember-Leaflet to support the layers control? I think I need to create layers outside of the `EmberLeaflet.MapView` scope, so that I can also create a Layers control. At least I think I need to create layers separately because I can't pass layer class definitions to both map and control. The layers must already be created before.
What would be the best approach for this?

Another thing that occured to me is that using the layers control kind of breaks the childLayers `CollectionLayer` in the `EmberLeaflet.MapView`. When you activate a layer through the control, the control adds the layer directly on the map and the `childLayers` no longer reflects the leaflet map.
Don't know what kind of problems this may create, but maybe the eventual solution would be to use the `baselayerchange` / `overlayadd` / `overlayremove` events, or event the `layeradd` event. (Check [map events](http://leafletjs.com/reference.html#map-events)).

Having a layers control is something very common and a very important feature in a map. So, after we solve this, we should include an example in the demo page.

**Comment by lminko** [comment]
+1 for LayerControls.

**Comment by lminko** [comment]
+1 for LayersControl.
