### ISSUE TITLE
Add/Remove MarkerCollectionLayer

### ISSUE THREAD

**Issue by brili** [gabesmed/ember-leaflet#90]
If there are multiple MarkerCollectionLayers how can we remove and add based on some event like click. I have MarkerCollectionLayers for different categories binded to their contents. How can we add/ remove these layers from the map or at least hide/show

**Comment by gagoman** [comment]
Hello. I've faced similar issue. And here's an example:

    zoomend: function () {
        var zoom = this.get('_layer._zoom'),
            childLayers = this.get('childLayers');

        childLayers.forEach(function (layer) {
            if (layer.get('hideAtRange') !== undefined) {
                if (layer.needToHide(zoom)) {
                  layer.hide();
                } else {
                  layer.show();
                }
            }
        });
    },

Where `hide` and `show` are methods of mixin:

    hide: function () {
        if (this.get('_hidden')) {
          return;
        }
        this.toggleProperty('_hidden');
        this._destroyLayer();
    },

    show: function () {
        if (!this.get('_hidden')) {
          return;
        }
        this.toggleProperty('_hidden');
        this._createLayer();
    },

**Comment by brili** [comment]
!
