### ISSUE TITLE
Class reference broken

### ISSUE THREAD

**Issue by Rahien** [gabesmed/ember-leaflet#91]
Hi,

Very nice library and examples page! However, it seems the class reference is broken, I get 404's for the libraries, e.g. http://gabesmed.github.io/ember-leaflet/docs/assets/js/api-filter.js and I don't get any content when I click on any of the classes...

Could you have a look?

Thanks!

**Comment by gabesmed** [comment]
Hm, not really sure about what you mean here. That I think is utility library for the jsdoc?
These links seem to work:

http://gabesmed.github.io/ember-leaflet/docs/
http://gabesmed.github.io/ember-leaflet/docs/classes/EmberLeaflet.LayerMixin.html
