### ISSUE TITLE
Leadership & direction for EmberLeaflet

### ISSUE THREAD

**Issue by gabesmed** [gabesmed/ember-leaflet#93]
Hey all! So in an exciting new development, @twokul, an accomplished Ember and Ember-CLI developer, has offered to pitch in with leadership & maintenance for EmberLeaflet! I've added him as an admin, along with @miguelcobain in a long-deserved promotion! :) Thank you all so much for seizing the reins as I've had less time to commit to the library. I very much want to help out and continue to be involved in this project, but I also don't want to hold things back for the major retrofitting that needs to be done for ES6 modules, Ember-CLI compliance, and maintaining compatibility for new versions of ember.

I want to make sure that we have a unified direction even with lots of new cooks in the kitchen, so I figured I'd open this thread and we can all discuss!

@codefox421 @miguelcobain @twokul

**Comment by miguelcobain** [comment]
My pleasure. :)
I remember starting this idea a long time ago. Then you arranged this all in a brilliant composable approach. Thank you. I learned a lot from this project.

I'll be using this library extensively in a near future, so I may be contributing more often soon.

Thanks. Let's make this happen. Ember-cli is at sight. :)

**Comment by twokul** [comment]
@gabesmed @miguelcobain me is excite! maybe we should do a quick google hangout to chat about the direction?

**Comment by gabesmed** [comment]
Awesome, sounds good to me! Would maybe tues 2/17 work? I could do early (9am) tomorrow the 13th too if that's better for all.

**Comment by miguelcobain** [comment]
I'm available since 10 am GMT, week days (please). :D

**Comment by twokul** [comment]
@miguelcobain @gabesmed can you guys send me your email addresses (alex.navasardyan@gmail.com), I'll schedule a hangout.

**Comment by gabesmed** [comment]
I'm in for 9am tomorrow (tues)!

**Comment by twokul** [comment]
@gabesmed invitation sent. did you see it?

**Comment by miguelcobain** [comment]
I did!

**Comment by gabesmed** [comment]
yep! i'm in the link?

**Comment by gabesmed** [comment]
we had some trouble with hangouts, skype us? gabe.smedresman

**Comment by gabesmed** [comment]
:+1:
